### ISSUE TITLE
Hangs when deleting policies

### ISSUE THREAD

**Issue by tobalo** [AnykeyNL/OCI-SuperDelete#17]
I have admin level access to tenancy but script hangs when it gets to delete policies portion. I can remediate it by manually deleting policies then script will detect and continue. not sure why it hangs given i have appropriate access.

**Comment by AnykeyNL** [comment]
That is very strange. Have you tried waiting for a while to see if there is a timeout error, else I suspect an endless loop. I will check.

**Comment by tobalo** [comment]
Looks like it hangs on infinite error loop. I would report error but I
don’t get descriptive error output. Workaround is to go in and manually
delete the policies as it runs, thought I’d share with dev team my
experience.

Very useful script though for managing large tenancies.

**Comment by AnykeyNL** [comment]
I removed the loop, should not hang anymore in any situation.
