### ISSUE TITLE
boot Volume cannot be deleted while volume replication is enabled

### ISSUE THREAD

**Issue by wanax1** [AnykeyNL/OCI-SuperDelete#26]
Hi guys,

Because "boot Volume cannot be deleted while volume replication is enabled. Disable volume replication before deleting the volume."
So please add the following four lines to disable volume replication before the thirty-second line "print("Deleting: {}".format(itemstatus.display_name))"                     

      print("Disable volume replication")
      object.update_boot_volume(
               boot_volume_id=itemstatus.id,
               update_boot_volume_details=oci.core.models.UpdateBootVolumeDetails(boot_volume_replicas=[]))
                            
Regards,
Gary Wan

**Comment by adizohar** [comment]
I pushed, this item can be closed after the merge

**Comment by AnykeyNL** [comment]
Add support for deleting replications for block, boot and group volumes, including waiting on replication to be terminated before volume to be deleted.
