### ISSUE TITLE
can't delete bucket when multipart upload in-progress 

### ISSUE THREAD

**Issue by wanax1** [AnykeyNL/OCI-SuperDelete#30]
Because the issue "can't delete bucket when multipart upload in-progress ", so I supplement a few lines of code in the ObjectStorage.py, please check the attachment.
Would you update it into the ObjectStorage.py, thanks.
Regards
Gary Wan
[ObjectStorage.py.txt](https://github.com/AnykeyNL/OCI-SuperDelete/files/7379739/ObjectStorage.py.txt)

**Comment by adizohar** [comment]
I did some changes to those objects, happy to check and added yours (if mine not fixed this issue already)

**Comment by wanax1** [comment]
Great, thanks.
