### ISSUE TITLE
delete GoldenGate

### ISSUE THREAD

**Issue by wanax1** [AnykeyNL/OCI-SuperDelete#31]
Hi guys,
I make a GoldenGate.py to delete GoldenGate, would you merge it into the code, thanks.
Regards,
Gary Wan
[GoldenGate.py.txt](https://github.com/AnykeyNL/OCI-SuperDelete/files/7379766/GoldenGate.py.txt)

**Comment by AnykeyNL** [comment]
good test :-)

**Comment by adizohar** [comment]
I added the code, testing and will push soon.
