### ISSUE TITLE
AttributeError: module 'oci' has no attribute 'nosql'

### ISSUE THREAD

**Issue by sergiorochalopes** [AnykeyNL/OCI-SuperDelete#4]
Hey guys!

$ python3 delete.py -c ocid1.compartment.oc1..aaaaa.......

(lists and runs everything correctly.. until...)

--[ Deleting Nosql tables ]--
Traceback (most recent call last):
  File "delete.py", line 128, in <module>
    DeleteNosql(config, processCompartments)
  File "/opt/repo/OCI-SuperDelete/ocimodules/Nosql.py", line 8, in DeleteNosql
    object = oci.nosql.NosqlClient(config)
AttributeError: module 'oci' has no attribute 'nosql'
--> and exits/breaks here <--

To be able to run the rest of the script I commented out line 128:: 
        print("\n--[ -NOT- Deleting Nosql tables ]--")
       ####### DeleteNosql(config, processCompartments)

Cheers!
@srochalo

**Comment by AnykeyNL** [comment]
Thanks, think this occurs in regions that do not have the service. I will fix it in the code so it does not error out.

**Comment by sergiorochalopes** [comment]
I am running this on Frankfurt region.

**Comment by sergiorochalopes** [comment]
Got another one - Data Science module

--[ Deleting DataScience Components ]--
Traceback (most recent call last):
  File "../delete.py", line 116, in <module>
    DeleteNotebooks(config, processCompartments)
  File "/opt/repo/OCI-SuperDelete/ocimodules/DataScience.py", line 8, in DeleteNotebooks
    object = oci.data_science.DataScienceClient(config)
AttributeError: module 'oci' has no attribute 'data_science'

**Comment by AnykeyNL** [comment]
Sorry I was not looking correctly.

errors: 
module 'oci' has no attribute 'data_science'
module 'oci' has no attribute 'nosql'

means your python oci library is not up to date.

**Comment by AnykeyNL** [comment]
please re-open issue if issue is not resolved by upgrading oci python library.
