### ISSUE TITLE
ModuleNotFoundError: No module named 'ocimodules'

### ISSUE THREAD

**Issue by rheadrickTSC** [AnykeyNL/OCI-SuperDelete#58]
What am I doing wrong here?

 (us-ashburn-1)$ python3 ./delete.py -c ocid1.compartment.oc1..aaaaaaaa........
Traceback (most recent call last):
  File "./delete.py", line 25, in <module>
    from ocimodules.functions import *
ModuleNotFoundError: No module named 'ocimodules'
rheadrick@cloudshell:~ (us-ashburn-1)$

**Comment by AnykeyNL** [comment]
I think you only downloaded the delete.py file, you need to download the entire repo
